id: P000385
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W17836
  title: གསུང་སྒྲོས་ཕན་བྱེད་རིག་པའི་མཛོད།
  author: ''
  volumes:
    5dec6cdc403c49c999eb4fc1a9a26be2:
      image_group_id: I1GS57578
      title: Volume 1 of gsung sgros phan byed rig pa'i mdzod
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
